apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      run: todo-app-flask
  template:
    metadata:
      labels:
        run: todo-app-flask
    spec:
      containers:
        - name: todo-app-flask
          image: himanshukingstorm/todo-app-py-flask:v.version
          ports:
            - containerPort: 5000
            
---
# Service YAML FILE

apiVersion: v1
kind: Service
metadata:
  name: todo-app-flask
  labels:
    run: todo-app-flask

spec:
  selector:
    run: todo-app-flask
  type: NodePort
  ports:
    - port: 5000
      protocol: "TCP"
      targetPort: 5000
      nodePort: 30304
